package com.university.internship.service;

import com.university.internship.model.InternshipAgreement;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

@Service
public class PdfGenerationService {

    @Value("${file.upload-dir}")
    private String uploadDir;


    public String generateAgreementPdf(InternshipAgreement agreement) throws IOException {
        // Create upload directory if it doesn't exist
        Path uploadPath = Paths.get(uploadDir);
        if (!Files.exists(uploadPath)) {
            Files.createDirectories(uploadPath);
        }

        // Generate unique filename
        String filename = "agreement_" + UUID.randomUUID().toString() + ".pdf";
        Path filePath = uploadPath.resolve(filename);

        // Create PDF document
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage();
            document.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                // Set font
                PDType1Font font = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
                PDType1Font boldFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);

                float margin = 50;
                float yPosition = 750;
                float leading = 20;

                // Title
                contentStream.beginText();
                contentStream.setFont(boldFont, 18);
                contentStream.newLineAtOffset(margin, yPosition);
                contentStream.showText("INTERNSHIP AGREEMENT");
                contentStream.endText();

                yPosition -= leading * 2;

                // Agreement details
                contentStream.beginText();
                contentStream.setFont(font, 12);
                contentStream.newLineAtOffset(margin, yPosition);
                
                String[] lines = {
                    "Agreement ID: " + agreement.getId(),
                    "Generation Date: " + agreement.getGenerationDate().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
                    "",
                    "STUDENT INFORMATION:",
                    "Name: " + agreement.getApplication().getStudent().getFirstName() + " " + 
                             agreement.getApplication().getStudent().getLastName(),
                    "Email: " + agreement.getApplication().getStudent().getEmail(),
                    "Field of Study: " + (agreement.getApplication().getStudent().getStudentProfile() != null ? 
                                         agreement.getApplication().getStudent().getStudentProfile().getFieldOfStudy() : "N/A"),
                    "University: " + (agreement.getApplication().getStudent().getStudentProfile() != null ? 
                                     agreement.getApplication().getStudent().getStudentProfile().getUniversity() : "N/A"),
                    "",
                    "COMPANY INFORMATION:",
                    "Company: " + (agreement.getApplication().getInternshipOffer().getCompany().getCompanyProfile() != null ? 
                                  agreement.getApplication().getInternshipOffer().getCompany().getCompanyProfile().getCompanyName() : "N/A"),
                    "",
                    "INTERNSHIP DETAILS:",
                    "Position: " + agreement.getApplication().getInternshipOffer().getTitle(),
                    "Duration: " + agreement.getApplication().getInternshipOffer().getDurationInMonths() + " months",
                    "Start Date: " + agreement.getApplication().getInternshipOffer().getStartDate(),
                    "Location: " + agreement.getApplication().getInternshipOffer().getLocation(),
                    "",
                    "STATUS: " + agreement.getStatus(),
                    "",
                    "This agreement certifies that the above student will undertake an internship",
                    "with the specified company under the terms and conditions outlined above.",
                    "",
                    "Generated by University Internship Management System"
                };

                for (String line : lines) {
                    contentStream.showText(line);
                    contentStream.newLineAtOffset(0, -leading);
                }

                contentStream.endText();

                // Add signature areas
                yPosition = 200;
                contentStream.beginText();
                contentStream.setFont(font, 10);
                contentStream.newLineAtOffset(margin, yPosition);
                contentStream.showText("Student Signature: _________________________    Date: __________");
                contentStream.newLineAtOffset(0, -leading * 2);
                contentStream.showText("Company Representative: ___________________    Date: __________");
                contentStream.newLineAtOffset(0, -leading * 2);
                contentStream.showText("Academic Supervisor: ______________________    Date: __________");
                contentStream.endText();
            }

            // Save the document
            document.save(filePath.toFile());
        }

        return filename;
    }
}
